name: Build

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm -r install

    - name: build
      run: pnpm run package

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
          release/build/*

    - name: Publish releases
      env:
        # This is used for uploading release assets to github
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm exec electron-builder -- --publish always --win --mac --linux
