name: Build

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Build
        run: pnpm run package

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install semantic-release
        run: pnpm install semantic-release @semantic-release/changelog @semantic-release/git -D

      - name: Semantic Release
        run: npx semantic-release

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
